import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("ROOT_LAYOUT_VERSION_48b713a");
  const commitHash = "3c1d38f";
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {/* Debug: visible version marker */}
        <div
          id="app-version"
          style={{
            position: 'fixed',
            bottom: '4px',
            right: '4px',
            background: 'rgba(0,0,0,0.7)',
            color: '#0f0',
            padding: '2px 6px',
            fontSize: '10px',
            fontFamily: 'monospace',
            zIndex: 99999,
            pointerEvents: 'none',
            opacity: 0.8,
          }}
        >
          v={commitHash}
        </div>
      </body>
    </html>
  );
}
