export const DEPARTMENTS_BY_COUNTRY: Record<string, { code: string; name: string }[]> = {
  AR: [
    { code: "BA", name: "Buenos Aires" },
    { code: "CA", name: "Catamarca" },
    { code: "CH", name: "Chaco" },
    { code: "CT", name: "Chubut" },
    { code: "CB", name: "Córdoba" },
    { code: "CR", name: "Corrientes" },
    { code: "ER", name: "Entre Ríos" },
    { code: "FO", name: "Formosa" },
    { code: "JY", name: "Jujuy" },
    { code: "LP", name: "La Pampa" },
    { code: "LR", name: "La Rioja" },
    { code: "MZ", name: "Mendoza" },
    { code: "MI", name: "Misiones" },
    { code: "NQ", name: "Neuquén" },
    { code: "RN", name: "Río Negro" },
    { code: "SA", name: "Salta" },
    { code: "SJ", name: "San Juan" },
    { code: "SL", name: "San Luis" },
    { code: "SC", name: "Santa Cruz" },
    { code: "SF", name: "Santa Fe" },
    { code: "SE", name: "Santiago del Estero" },
    { code: "TF", name: "Tierra del Fuego" },
    { code: "TU", name: "Tucumán" },
  ],
  BZ: [
    { code: "BZ", name: "Belize" },
    { code: "CY", name: "Cayo" },
    { code: "CZ", name: "Corozal" },
    { code: "OW", name: "Orange Walk" },
    { code: "SC", name: "Stann Creek" },
    { code: "TO", name: "Toledo" },
  ],
  BO: [
    { code: "B", name: "Beni" },
    { code: "C", name: "Cochabamba" },
    { code: "CH", name: "Chuquisaca" },
    { code: "L", name: "La Paz" },
    { code: "O", name: "Oruro" },
    { code: "N", name: "Pando" },
    { code: "P", name: "Potosí" },
    { code: "S", name: "Santa Cruz" },
    { code: "T", name: "Tarija" },
  ],
  BR: [
    { code: "AC", name: "Acre" },
    { code: "AL", name: "Alagoas" },
    { code: "AP", name: "Amapá" },
    { code: "AM", name: "Amazonas" },
    { code: "BA", name: "Bahia" },
    { code: "CE", name: "Ceará" },
    { code: "DF", name: "Distrito Federal" },
    { code: "ES", name: "Espírito Santo" },
    { code: "GO", name: "Goiás" },
    { code: "MA", name: "Maranhão" },
    { code: "MT", name: "Mato Grosso" },
    { code: "MS", name: "Mato Grosso do Sul" },
    { code: "MG", name: "Minas Gerais" },
    { code: "PA", name: "Pará" },
    { code: "PB", name: "Paraíba" },
    { code: "PR", name: "Paraná" },
    { code: "PE", name: "Pernambuco" },
    { code: "PI", name: "Piauí" },
    { code: "RJ", name: "Rio de Janeiro" },
    { code: "RN", name: "Rio Grande do Norte" },
    { code: "RS", name: "Rio Grande do Sul" },
    { code: "RO", name: "Rondônia" },
    { code: "RR", name: "Roraima" },
    { code: "SC", name: "Santa Catarina" },
    { code: "SP", name: "São Paulo" },
    { code: "SE", name: "Sergipe" },
    { code: "TO", name: "Tocantins" },
  ],
  CL: [
    { code: "AI", name: "Aysén" },
    { code: "AN", name: "Antofagasta" },
    { code: "AP", name: "Arica y Parinacota" },
    { code: "AT", name: "Atacama" },
    { code: "BI", name: "Biobío" },
    { code: "CO", name: "Coquimbo" },
    { code: "LI", name: "Libertador General Bernardo O'Higgins" },
    { code: "LL", name: "Los Lagos" },
    { code: "LR", name: "Los Ríos" },
    { code: "MA", name: "Magallanes" },
    { code: "ML", name: "Maule" },
    { code: "NB", name: "Ñuble" },
    { code: "RM", name: "Región Metropolitana de Santiago" },
    { code: "TA", name: "Tarapacá" },
    { code: "VS", name: "Valparaíso" },
  ],
  CO: [
    { code: "AMA", name: "Amazonas" },
    { code: "ANT", name: "Antioquia" },
    { code: "ARA", name: "Arauca" },
    { code: "ATL", name: "Atlántico" },
    { code: "BOL", name: "Bolívar" },
    { code: "BOY", name: "Boyacá" },
    { code: "CAL", name: "Caldas" },
    { code: "CAQ", name: "Caquetá" },
    { code: "CAS", name: "Casanare" },
    { code: "CAU", name: "Cauca" },
    { code: "CES", name: "Cesar" },
    { code: "CHO", name: "Chocó" },
    { code: "COR", name: "Córdoba" },
    { code: "CUN", name: "Cundinamarca" },
    { code: "GUI", name: "Guainía" },
    { code: "GUV", name: "Guaviare" },
    { code: "HUI", name: "Huila" },
    { code: "LAG", name: "La Guajira" },
    { code: "MAG", name: "Magdalena" },
    { code: "MET", name: "Meta" },
    { code: "NAR", name: "Nariño" },
    { code: "NSA", name: "Norte de Santander" },
    { code: "PUT", name: "Putumayo" },
    { code: "QUI", name: "Quindío" },
    { code: "RIS", name: "Risaralda" },
    { code: "SAP", name: "San Andrés y Providencia" },
    { code: "SAN", name: "Santander" },
    { code: "SUC", name: "Sucre" },
    { code: "TOL", name: "Tolima" },
    { code: "VAC", name: "Valle del Cauca" },
    { code: "VAU", name: "Vaupés" },
    { code: "VID", name: "Vichada" },
  ],
  CR: [
    { code: "SJ", name: "San José" },
    { code: "AL", name: "Alajuela" },
    { code: "CA", name: "Cartago" },
    { code: "HE", name: "Heredia" },
    { code: "GU", name: "Guanacaste" },
    { code: "PU", name: "Puntarenas" },
    { code: "LI", name: "Limón" },
  ],
  CU: [
    { code: "PRI", name: "Pinar del Río" },
    { code: "ART", name: "Artemisa" },
    { code: "MAY", name: "Mayabeque" },
    { code: "LV", name: "La Habana" },
    { code: "MT", name: "Matanzas" },
    { code: "CF", name: "Cienfuegos" },
    { code: "VC", name: "Villa Clara" },
    { code: "SS", name: "Sancti Spíritus" },
    { code: "CA", name: "Ciego de Ávila" },
    { code: "CM", name: "Camagüey" },
    { code: "LT", name: "Las Tunas" },
    { code: "GR", name: "Granma" },
    { code: "HG", name: "Holguín" },
    { code: "SC", name: "Santiago de Cuba" },
    { code: "GU", name: "Guantánamo" },
    { code: "IJ", name: "Isla de la Juventud" },
  ],
  EC: [
    { code: "A", name: "Azuay" },
    { code: "B", name: "Bolívar" },
    { code: "F", name: "Cañar" },
    { code: "C", name: "Carchi" },
    { code: "X", name: "Chimborazo" },
    { code: "H", name: "Chone" },
    { code: "D", name: "Cotopaxi" },
    { code: "E", name: "El Oro" },
    { code: "G", name: "Esmeraldas" },
    { code: "I", name: "Galápagos" },
    { code: "W", name: "Guayas" },
    { code: "K", name: "Imbabura" },
    { code: "L", name: "Loja" },
    { code: "M", name: "Los Ríos" },
    { code: "N", name: "Manabí" },
    { code: "O", name: "Morona Santiago" },
    { code: "S", name: "Napo" },
    { code: "Y", name: "Orellana" },
    { code: "P", name: "Pastaza" },
    { code: "Q", name: "Pichincha" },
    { code: "U", name: "Santa Elena" },
    { code: "R", name: "Santo Domingo de los Tsáchilas" },
    { code: "T", name: "Sucumbíos" },
    { code: "V", name: "Tungurahua" },
    { code: "Z", name: "Zamora Chinchipe" },
  ],
  SV: [
    { code: "AH", name: "Ahuachapán" },
    { code: "CB", name: "Cabañas" },
    { code: "CH", name: "Chalatenango" },
    { code: "CU", name: "Cuscatlán" },
    { code: "LB", name: "La Libertad" },
    { code: "PZ", name: "La Paz" },
    { code: "UN", name: "La Unión" },
    { code: "MO", name: "Morazán" },
    { code: "SM", name: "San Miguel" },
    { code: "SS", name: "San Salvador" },
    { code: "SV", name: "San Vicente" },
    { code: "SA", name: "Santa Ana" },
    { code: "SO", name: "Sonsonate" },
    { code: "US", name: "Usulután" },
  ],
  GT: [
    { code: "AV", name: "Alta Verapaz" },
    { code: "BV", name: "Baja Verapaz" },
    { code: "CM", name: "Chimaltenango" },
    { code: "CQ", name: "Chiquimula" },
    { code: "PG", name: "El Progreso" },
    { code: "ES", name: "Escuintla" },
    { code: "GU", name: "Guatemala" },
    { code: "HU", name: "Huehuetenango" },
    { code: "IZ", name: "Izabal" },
    { code: "JA", name: "Jalapa" },
    { code: "JU", name: "Jutiapa" },
    { code: "PE", name: "Petén" },
    { code: "QZ", name: "Quetzaltenango" },
    { code: "QC", name: "Quiché" },
    { code: "RE", name: "Retalhuleu" },
    { code: "SM", name: "Sacatepéquez" },
    { code: "SMK", name: "San Marcos" },
    { code: "SR", name: "Santa Rosa" },
    { code: "SO", name: "Sololá" },
    { code: "SU", name: "Suchitepéquez" },
    { code: "TO", name: "Totonicapán" },
    { code: "ZA", name: "Zacapa" },
  ],
  HN: [
    { code: "AT", name: "Atlántida" },
    { code: "CH", name: "Choluteca" },
    { code: "CL", name: "Colón" },
    { code: "CM", name: "Comayagua" },
    { code: "CP", name: "Copán" },
    { code: "CR", name: "Cortés" },
    { code: "EP", name: "El Paraíso" },
    { code: "FM", name: "Francisco Morazán" },
    { code: "GD", name: "Gracias a Dios" },
    { code: "IN", name: "Intibucá" },
    { code: "IB", name: "Islas de la Bahía" },
    { code: "PZ", name: "La Paz" },
    { code: "LE", name: "Lempira" },
    { code: "OC", name: "Ocotepeque" },
    { code: "OL", name: "Olancho" },
    { code: "SB", name: "Santa Bárbara" },
    { code: "VA", name: "Valle" },
    { code: "YO", name: "Yoro" },
  ],
  MX: [
    { code: "AGU", name: "Aguascalientes" },
    { code: "BCN", name: "Baja California" },
    { code: "BCS", name: "Baja California Sur" },
    { code: "CAM", name: "Campeche" },
    { code: "CHP", name: "Chiapas" },
    { code: "CHH", name: "Chihuahua" },
    { code: "CDMX", name: "Ciudad de México" },
    { code: "COA", name: "Coahuila" },
    { code: "COL", name: "Colima" },
    { code: "DUR", name: "Durango" },
    { code: "GUA", name: "Guanajuato" },
    { code: "GRO", name: "Guerrero" },
    { code: "HID", name: "Hidalgo" },
    { code: "JAL", name: "Jalisco" },
    { code: "MEX", name: "Estado de México" },
    { code: "MIC", name: "Michoacán" },
    { code: "MOR", name: "Morelos" },
    { code: "NAY", name: "Nayarit" },
    { code: "NLE", name: "Nuevo León" },
    { code: "OAX", name: "Oaxaca" },
    { code: "PUE", name: "Puebla" },
    { code: "QUE", name: "Querétaro" },
    { code: "ROO", name: "Quintana Roo" },
    { code: "SLP", name: "San Luis Potosí" },
    { code: "SIN", name: "Sinaloa" },
    { code: "SON", name: "Sonora" },
    { code: "TAB", name: "Tabasco" },
    { code: "TAM", name: "Tamaulipas" },
    { code: "TLA", name: "Tlaxcala" },
    { code: "VER", name: "Veracruz" },
    { code: "YUC", name: "Yucatán" },
    { code: "ZAC", name: "Zacatecas" },
  ],
  NI: [
    { code: "BO", name: "Boaco" },
    { code: "CA", name: "Carazo" },
    { code: "CI", name: "Chinandega" },
    { code: "CT", name: "Chontales" },
    { code: "ES", name: "Estelí" },
    { code: "GR", name: "Granada" },
    { code: "JI", name: "Jinotega" },
    { code: "LE", name: "León" },
    { code: "MD", name: "Madriz" },
    { code: "MN", name: "Managua" },
    { code: "MY", name: "Masaya" },
    { code: "MT", name: "Matagalpa" },
    { code: "NS", name: "Nueva Segovia" },
    { code: "RACCN", name: "RACCN" },
    { code: "RACCS", name: "RACCS" },
    { code: "RS", name: "Río San Juan" },
    { code: "RI", name: "Rivas" },
  ],
  PA: [
    { code: "BT", name: "Bocas del Toro" },
    { code: "CL", name: "Coclé" },
    { code: "CN", name: "Colón" },
    { code: "CH", name: "Chiriquí" },
    { code: "DA", name: "Darién" },
    { code: "HE", name: "Herrera" },
    { code: "LS", name: "Los Santos" },
    { code: "PA", name: "Panamá" },
    { code: "PO", name: "Panamá Oeste" },
    { code: "VG", name: "Veraguas" },
  ],
  PY: [
    { code: "AG", name: "Alto Paraná" },
    { code: "AM", name: "Alto Paraguay" },
    { code: "AS", name: "Amambay" },
    { code: "BQ", name: "Boquerón" },
    { code: "CG", name: "Caaguazú" },
    { code: "CZ", name: "Caazapá" },
    { code: "CN", name: "Canindeyú" },
    { code: "CE", name: "Central" },
    { code: "CC", name: "Concepción" },
    { code: "CR", name: "Cordillera" },
    { code: "GU", name: "Guairá" },
    { code: "IT", name: "Itapúa" },
    { code: "MI", name: "Misiones" },
    { code: "NE", name: "Ñeembucú" },
    { code: "PG", name: "Paraguarí" },
    { code: "PH", name: "Presidente Hayes" },
    { code: "SP", name: "San Pedro" },
  ],
  PE: [
    { code: "AMA", name: "Amazonas" },
    { code: "ANC", name: "Ancash" },
    { code: "APU", name: "Apurímac" },
    { code: "ARE", name: "Arequipa" },
    { code: "AYA", name: "Ayacucho" },
    { code: "CAJ", name: "Cajamarca" },
    { code: "CUS", name: "Cusco" },
    { code: "CAL", name: "El Callao" },
    { code: "HUV", name: "Huancavelica" },
    { code: "HUC", name: "Huánuco" },
    { code: "ICA", name: "Ica" },
    { code: "JUN", name: "Junín" },
    { code: "LAL", name: "La Libertad" },
    { code: "LAM", name: "Lambayeque" },
    { code: "LIM", name: "Lima" },
    { code: "LOR", name: "Loreto" },
    { code: "MDD", name: "Madre de Dios" },
    { code: "MOQ", name: "Moquegua" },
    { code: "LMA", name: "Municipalidad Metropolitana de Lima" },
    { code: "PAS", name: "Pasco" },
    { code: "PIU", name: "Piura" },
    { code: "PUN", name: "Puno" },
    { code: "SAM", name: "San Martín" },
    { code: "TAC", name: "Tacna" },
    { code: "TUM", name: "Tumbes" },
    { code: "UCA", name: "Ucayali" },
  ],
  DO: [
    { code: "DN", name: "Distrito Nacional (Santo Domingo)" },
    { code: "AZ", name: "Azua" },
    { code: "BH", name: "Baoruco" },
    { code: "BR", name: "Barahona" },
    { code: "DA", name: "Dajabón" },
    { code: "DU", name: "Distrito Nacional" },
    { code: "SD", name: "Santo Domingo" },
    { code: "ST", name: "Santiago" },
    { code: "VG", name: "Valverde" },
    { code: "EP", name: "Elías Piña" },
    { code: "EPM", name: "El Seibo" },
    { code: "HT", name: "Hato Mayor" },
    { code: "HM", name: "Hermanas Mirabal" },
    { code: "IN", name: "Independencia" },
    { code: "AL", name: "La Altagracia" },
    { code: "RO", name: "La Romana" },
    { code: "VE", name: "La Vega" },
    { code: "MT", name: "María Trinidad Sánchez" },
    { code: "MN", name: "Monseñor Nouel" },
    { code: "MC", name: "Monte Cristi" },
    { code: "MP", name: "Monte Plata" },
    { code: "PD", name: "Pedernales" },
    { code: "PR", name: "Peravia" },
    { code: "PU", name: "Puerto Plata" },
    { code: "SP", name: "Sánchez Ramírez" },
    { code: "SM", name: "San Cristóbal" },
    { code: "SJ", name: "San Juan" },
    { code: "PM", name: "San Pedro de Macorís" },
    { code: "SZ", name: "Santiago Rodríguez" },
    { code: "SN", name: "Santiago" },
    { code: "VP", name: "Valverde" },
  ],
  UY: [
    { code: "AR", name: "Artigas" },
    { code: "CA", name: "Canelones" },
    { code: "CL", name: "Cerro Largo" },
    { code: "CO", name: "Colonia" },
    { code: "DU", name: "Durazno" },
    { code: "FS", name: "Flores" },
    { code: "FA", name: "Florida" },
    { code: "LA", name: "Lavalleja" },
    { code: "MA", name: "Maldonado" },
    { code: "MO", name: "Montevideo" },
    { code: "PA", name: "Paysandú" },
    { code: "RN", name: "Río Negro" },
    { code: "RV", name: " Rivera" },
    { code: "RO", name: "Rocha" },
    { code: "SA", name: "Salto" },
    { code: "SJ", name: "San José" },
    { code: "SO", name: "Soriano" },
    { code: "TA", name: "Tacuarembó" },
    { code: "TT", name: "Treinta y Tres" },
  ],
  VE: [
    { code: "AM", name: "Amazonas" },
    { code: "AN", name: "Anzoátegui" },
    { code: "AP", name: "Apure" },
    { code: "AR", name: "Aragua" },
    { code: "BA", name: "Barinas" },
    { code: "BL", name: "Bolívar" },
    { code: "CA", name: "Carabobo" },
    { code: "CZ", name: "Cojedes" },
    { code: "AM", name: "Delta Amacuro" },
    { code: "DC", name: "Distrito Capital" },
    { code: "FA", name: "Falcón" },
    { code: "GU", name: "Guárico" },
    { code: "L", name: "Lara" },
    { code: "M", name: "Mérida" },
    { code: "MIR", name: "Miranda" },
    { code: "MO", name: "Monagas" },
    { code: "N", name: "Nueva Esparta" },
    { code: "P", name: "Portuguesa" },
    { code: "SU", name: "Sucre" },
    { code: "T", name: "Táchira" },
    { code: "TA", name: "Trujillo" },
    { code: "V", name: "Vargas" },
    { code: "Y", name: "Yaracuy" },
    { code: "Z", name: "Zulia" },
  ],
  PR: [ // Puerto Rico - municipios
    { code: "ADJ", name: "Adjuntas" },
    { code: "AGU", name: "Aguada" },
    { code: "AGU", name: "Aguadilla" },
    { code: "ARE", name: "Arecibo" },
    { code: "ARB", name: "Arroyo" },
    { code: "BAR", name: "Barceloneta" },
    { code: "BAY", name: "Bayamón" },
    { code: "CAB", name: "Cabo Rojo" },
    { code: "CAG", name: "Caguas" },
    { code: "CAM", name: "Camuy" },
    { code: "CAN", name: "Canóvanas" },
    { code: "CAR", name: "Carolina" },
    { code: "CAT", name: "Cataño" },
    { code: "CAY", name: "Cayey" },
    { code: "CEI", name: "Ceiba" },
    { code: "CIA", name: "Ciales" },
    { code: "CID", name: "Cidra" },
    { code: "COA", name: "Coamo" },
    { code: "COM", name: "Comerío" },
    { code: "COR", name: "Corozal" },
    { code: "CUL", name: "Culebra" },
    { code: "DOR", name: "Dorado" },
    { code: "FAJ", name: "Fajardo" },
    { code: "FLO", name: "Florida" },
    { code: "GUA", name: "Guánica" },
    { code: "GUA", name: "Guayama" },
    { code: "GUY", name: "Guayanilla" },
    { code: "GUR", name: "Guaynabo" },
    { code: "GMA", name: "Gurabo" },
    { code: "HEL", name: "Hatillo" },
    { code: "HUM", name: "Humacao" },
    { code: "IBA", name: " Isabela" },
    { code: "JAY", name: "Jayuya" },
    { code: "JUA", name: "Juana Díaz" },
    { code: "JUN", name: "Juncos" },
    { code: "LPA", name: "Lajas" },
    { code: "LAR", name: "Lares" },
    { code: "LAS", name: "Las Marías" },
    { code: "LSB", name: "Las Piedras" },
    { code: "LOI", name: "Loíza" },
    { code: "LUQ", name: "Luquillo" },
    { code: "MAN", name: "Manatí" },
    { code: "MAR", name: "Maricao" },
    { code: "MAU", name: "Maunabo" },
    { code: "MAY", name: "Mayagüez" },
    { code: "MOC", name: "Moca" },
    { code: "MOR", name: "Morovis" },
    { code: "NAG", name: "Naguabo" },
    { code: "NAR", name: "Naranjito" },
    { code: "OCO", name: "Orocovis" },
    { code: "PAT", name: "Patillas" },
    { code: "PEN", name: "Peñuelas" },
    { code: "PON", name: "Ponce" },
    { code: "QUE", name: "Quebradillas" },
    { code: "RIN", name: "Rincón" },
    { code: "RIO", name: "Río Grande" },
    { code: "SAB", name: "Sabana Grande" },
    { code: "SAL", name: "Salinas" },
    { code: "SBG", name: "San Germán" },
    { code: "SJA", name: "San Juan" },
    { code: "SLU", name: "San Lorenzo" },
    { code: "SMA", name: "San Sebastián" },
    { code: "SAN", name: "Santa Isabel" },
    { code: "TOA", name: "Toa Alta" },
    { code: "TOB", name: "Toa Baja" },
    { code: "TRU", name: "Trujillo Alto" },
    { code: "UTU", name: "Utuado" },
    { code: "VEG", name: "Vega Alta" },
    { code: "VEB", name: "Vega Baja" },
    { code: "VIA", name: "Vieques" },
    { code: "VIL", name: "Villalba" },
    { code: "YAB", name: "Yabucoa" },
    { code: "YAU", name: "Yauco" },
  ],
};
